cider: 24
dns: 8.8.8.8
firewalls:
- http
- https
- ntp
gateway: 172.25.2.1
hostanme: control
ip: 172.25.2.48
packages:
- httpd
- php
- chrony
services:
- httpd
- chrony
users:
- comment: WebAdminUser
  name: webadmin
- comment: ContentUPLoadUser
  name: upadmin
